### ISSUE TITLE
Propuesta de cambio

### ISSUE THREAD

**Issue by acasella03** [JorgeAmestoy/JugandoConPullRequest#1]
Hola Jorge, acabo de hacer un cambio, por favor revisalo, gracias.

**Comment by JorgeAmestoy** [comment]
Hola Angi. Me gusta la idea pero me parece algo muy básico, creo que podemos pensar en algo mejor

**Comment by acasella03** [comment]
@JorgeAmestoy hice énfasis con signos de exclamación para marcar su importancia.

**Comment by JorgeAmestoy** [comment]
@acasella03 perfecto. Gracias.
