### ISSUE TITLE
Cambio de código

### ISSUE THREAD

**Issue by JorgeAmestoy** [JorgeAmestoy/JugandoConPullRequest#3]
Hola @acasella03 , he modificado el código añadiendo la misma frase pero en inglés, qué opinas?

**Comment by acasella03** [comment]
@JorgeAmestoy me parece que puedes agregar otro idioma a parte del inglés, escribe también uno en italiano.

**Comment by JorgeAmestoy** [comment]
@acasella03 vale, perfecto.
